# Generated by Django 3.1.2 on 2020-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_history_owner', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_history_session', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_history_film_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('purchase_history_price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('purchase_history_film_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_history_film_title', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_history_film_friendly_title', models.CharField(blank=True, max_length=254, null=True)),
                ('purchase_history_film_box_cover_url', models.URLField(default='', max_length=254)),
                ('purchase_history_film_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('purchase_history_film_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=5)),
                ('purchase_history_film_product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
