# Generated by Django 3.1.2 on 2020-11-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_results', '0002_auto_20201106_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_username', models.CharField(blank=True, max_length=254, null=True)),
                ('up_first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('up_last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('up_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('up_address_line1', models.CharField(blank=True, max_length=254, null=True)),
                ('up_address_line2', models.CharField(blank=True, max_length=254, null=True)),
                ('up_address_line3', models.CharField(blank=True, max_length=254, null=True)),
                ('up_post_code', models.CharField(blank=True, max_length=254, null=True)),
                ('up_country', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_purchase_date', models.CharField(blank=True, max_length=20, null=True)),
                ('ph_cart_owner', models.CharField(blank=True, max_length=128, null=True)),
                ('ph_cart_film_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('ph_cart_price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ph_cart_film_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('ph_cart_film_title', models.CharField(blank=True, max_length=128, null=True)),
                ('ph_cart_film_friendly_title', models.CharField(blank=True, max_length=254, null=True)),
                ('ph_cart_film_box_cover_url', models.URLField(default='', max_length=254)),
                ('ph_cart_film_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('ph_cart_film_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=5)),
                ('ph_cart_film_product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('ph_cart_film_genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='search_results.genre')),
            ],
            options={
                'verbose_name_plural': 'User Purchase History',
            },
        ),
    ]
