# Generated by Django 3.1.2 on 2020-11-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='ph_purchase_date',
        ),
    ]
