# Generated by Django 3.1.2 on 2020-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(blank=True, max_length=254, null=True)),
                ('article_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('article_image', models.URLField(blank=True, max_length=254, null=True)),
                ('article_content', models.TextField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedAdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_date', models.DateField(auto_now=True)),
                ('classified_name', models.CharField(blank=True, max_length=254, null=True)),
                ('classified_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('classified_detail', models.TextField(blank=True, max_length=2000, null=True)),
                ('classified_image', models.URLField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classifieds Adds',
            },
        ),
        migrations.CreateModel(
            name='FrontPageCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_item', models.IntegerField(blank=True, null=True)),
                ('c_name', models.CharField(blank=True, max_length=254, null=True)),
                ('c_url', models.URLField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_name', models.CharField(blank=True, max_length=254, null=True)),
                ('snippet_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('snippet_detail', models.TextField(blank=True, null=True)),
                ('snippet_image', models.URLField(blank=True, max_length=254, null=True)),
                ('snippet_source_url', models.URLField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Snippets',
            },
        ),
    ]
