# Generated by Django 3.1.2 on 2020-11-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_live',
            field=models.BooleanField(default=True),
        ),
    ]
