# Generated by Django 3.1.2 on 2020-11-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_article_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
