# Generated by Django 3.1.2 on 2020-11-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201128_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassifiedAdds',
        ),
    ]
