# Generated by Django 3.1.2 on 2020-11-24 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField(default=datetime.date.today, verbose_name=datetime.date.today)),
                ('message_title', models.CharField(blank=True, max_length=254, null=True)),
                ('message_content', models.TextField(blank=True, max_length=2000, null=True)),
                ('messages_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Login Messages',
            },
        ),
    ]
