# Generated by Django 3.1.2 on 2020-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_success', '0002_auto_20201124_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmessages',
            name='messages_visible',
            field=models.BooleanField(default=True),
        ),
    ]
