# Generated by Django 3.1.2 on 2020-11-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_results', '0002_auto_20201106_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_owner', models.CharField(blank=True, max_length=20, null=True)),
                ('cart_session', models.CharField(blank=True, max_length=128, null=True)),
                ('cart_film_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('cart_film_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('cart_film_title', models.CharField(blank=True, max_length=128, null=True)),
                ('cart_film_friendly_title', models.CharField(blank=True, max_length=254, null=True)),
                ('cart_film_box_cover_url', models.URLField(default='', max_length=254)),
                ('cart_film_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('cart_film_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=5)),
                ('cart_film_product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('cart_film_stock_available', models.BooleanField(default=True)),
                ('cart_film_global_sale', models.BooleanField(default=True)),
                ('cart_film_clip_link', models.URLField(blank=True, max_length=254, null=True)),
                ('cart_film_genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='search_results.genre')),
            ],
            options={
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
    ]
