# Generated by Django 3.1.2 on 2020-11-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='cart_price_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
