# Generated by Django 3.1.2 on 2020-11-22 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_shoppingcartmodel_cart_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='cart_purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
    ]
