# Generated by Django 3.1.2 on 2020-11-26 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_shoppingcartmodel_cart_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='cart_purchase_date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
    ]
