# Generated by Django 3.1.2 on 2020-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20201126_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='cart_purchase_date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
