# Generated by Django 3.1.2 on 2020-11-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_auto_20201126_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='cart_purchase_date',
        ),
    ]
